[package]
name = "hcp-cli"
version = "0.1.0"
edition = "2021"
description = "CLI tool to explore Hashicorp Cloud"
authors = ["Piotr Kodzis"]
license = "MIT"
repository = "https://github.com/pkodzis/hcp-cli"
keywords = ["hashicorp", "terraform", "hcp", "cli", "cloud"]
categories = ["command-line-utilities"]

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
comfy-table = "7.1"
futures = "0.3"
env_logger = "0.11"
log = "0.4"
indicatif = "0.17"
dirs = "6.0.0"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.0"

[lib]
name = "hcp_cli"
path = "src/lib.rs"

[[bin]]
name = "hcp-cli"
path = "src/main.rs"
